In [1]:
import seaborn as sns
import matplotlib.pyplot as plt

from matplotlib import rc
%matplotlib inline
from matplotlib import font_manager
plt.style.use('default')
f_path = "C:/windows/Fonts/malgun.ttf"
ko_font = font_manager.FontProperties(fname=f_path).get_name()
rc('font', family='Malgun Gothic')
#plt.title('테스트')

In [2]:
from model.synthpop import Synthpop
import numpy as np
import pandas as pd
import glob
from table_evaluator import load_data, TableEvaluator
import sdmetrics

In [3]:
#Data Load

raw = pd.read_csv('C:/Users/82102/OneDrive - dongguk.edu/바탕 화면/캡스톤/data/rawdata.csv')

In [4]:
raw

,저소득층여부,나이,교육수준,혼인상태,가구형태,주택유형,주택점유형태,총생활비,총소득,가구서비스,노인서비스,아동서비스
0,2,78,중등,사별,단독,다가구용단독주택,자가,3300,0,이용,이용,해당없음
1,1,75,초등,사별,단독,다가구용단독주택,보증부월세,2868,2064,이용,이용,해당없음
2,1,81,대학,이혼,단독,일반단독주택,자가,1872,1200,이용,이용,해당없음
3,1,61,전문대,유배우,기타,다가구용단독주택,자가,6492,3216,이용,이용,해당없음
4,2,83,초등,사별,단독,일반아파트,비가구원명의주택,1020,324,이용,이용,해당없음
...,...,...,...,...,...,...,...,...,...,...,...,...
7860,1,42,전문대,유배우,기타,일반아파트,전세,4608,3630,이용,해당없음,이용
7861,1,46,대학,유배우,기타,일반아파트,자가,8580,5100,미이용,해당없음,이용
7862,1,47,대학,유배우,기타,일반아파트,자가,7140,5500,이용,해당없음,이용
7863,1,48,대학,유배우,기타,일반아파트,전세,6744,10350,미이용,해당없음,미이용
7864,1,59,대학,유배우,기타,일반아파트,전세,6168,7880,미이용,해당없음,해당없음

In [5]:
raw = raw.astype({'저소득층여부':'category',
                  '교육수준':'category',
                  "혼인상태": "category",
                  "가구형태": "category",
                  "주택유형": "category",
                  "주택점유형태": "category",
                  '가구서비스': 'category',
                  '노인서비스': 'category',
                  '아동서비스': 'category'})

In [6]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7865 entries, 0 to 7864
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   저소득층여부  7865 non-null   category
 1   나이      7865 non-null   int64
 2   교육수준    7865 non-null   category
 3   혼인상태    7865 non-null   category
 4   가구형태    7865 non-null   category
 5   주택유형    7865 non-null   category
 6   주택점유형태  7865 non-null   category
 7   총생활비    7865 non-null   int64
 8   총소득     7865 non-null   int64
 9   가구서비스   7865 non-null   category
 10  노인서비스   7865 non-null   category
 11  아동서비스   7865 non-null   category
dtypes: category(9), int64(3)
memory usage: 255.7 KB

In [7]:
from sklearn.model_selection import train_test_split

raw_0025,_ = train_test_split(raw, train_size = .025, random_state = 1)
raw_005,_ = train_test_split(raw, train_size = .05, random_state = 1)
raw_010,_ = train_test_split(raw, train_size = .1, random_state = 1)
raw_020,_ = train_test_split(raw, train_size = .2, random_state = 1)
raw_030,_ = train_test_split(raw, train_size = .3, random_state = 1)
raw_040,_ = train_test_split(raw, train_size = .4, random_state = 1)
raw_050,_ = train_test_split(raw, train_size = .5, random_state = 1)
raw_060,_ = train_test_split(raw, train_size = .6, random_state = 1)
raw_070,_ = train_test_split(raw, train_size = .7, random_state = 1)
raw_080,_ = train_test_split(raw, train_size = .8, random_state = 1)
raw_090,_ = train_test_split(raw, train_size = .9, random_state = 1)
raw_095,_ = train_test_split(raw, train_size = .95, random_state = 1)
raw_0975,_ = train_test_split(raw, train_size = .975, random_state = 1)
raw_0999,_ = train_test_split(raw, train_size = .999, random_state = 1)

# Generate Data_Synthpop

In [8]:
# 변수 타입 지정, 'int', 'float', 'datetime', 'category', 'bool' 만 가능
my_dtypes = {"저소득층여부": "category",
 "나이": "int",
 "교육수준": "category",
 "혼인상태": "category",
 "가구형태": "category",
 "주택유형": "category",
 "주택점유형태": "category",
 "총생활비": "int",
 "총소득": "int",
 '가구서비스': 'category',
 '노인서비스': 'category',
 '아동서비스': 'category'
}

my_dtypes

{'저소득층여부': 'category',
 '나이': 'int',
 '교육수준': 'category',
 '혼인상태': 'category',
 '가구형태': 'category',
 '주택유형': 'category',
 '주택점유형태': 'category',
 '총생활비': 'int',
 '총소득': 'int',
 '가구서비스': 'category',
 '노인서비스': 'category',
 '아동서비스': 'category'}

In [9]:
spop_0025 = Synthpop()
spop_0025.fit(raw_0025, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_0025 = spop_0025.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [10]:
spop_005 = Synthpop()
spop_005.fit(raw_005, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_005 = spop_005.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [11]:
spop_010 = Synthpop()
spop_010.fit(raw_010, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_010 = spop_010.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [12]:
spop_020 = Synthpop()
spop_020.fit(raw_020, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_020 = spop_020.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [13]:
spop_030 = Synthpop()
spop_030.fit(raw_030, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_030 = spop_030.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [14]:
spop_040 = Synthpop()
spop_040.fit(raw_040, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_040 = spop_040.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [15]:
spop_050 = Synthpop()
spop_050.fit(raw_050, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_050 = spop_050.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [16]:
spop_060 = Synthpop()
spop_060.fit(raw_060, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_060 = spop_060.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [17]:
spop_070 = Synthpop()
spop_070.fit(raw_070, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_070 = spop_070.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [18]:
spop_080 = Synthpop()
spop_080.fit(raw_080, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_080 = spop_080.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [19]:
spop_090 = Synthpop()
spop_090.fit(raw_090, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_090 = spop_090.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [20]:
spop_095 = Synthpop()
spop_095.fit(raw_095, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_095 = spop_095.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [21]:
spop_0975 = Synthpop()
spop_0975.fit(raw_0975, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_0975 = spop_0975.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [22]:
spop_0999 = Synthpop()
spop_0999.fit(raw_0999, dtypes = my_dtypes)

# Create synthetic data
nrow = len(raw)
synthetic_data_0999 = spop_0999.generate(nrow)

train_저소득층여부
train_나이
train_교육수준
train_혼인상태
train_가구형태
train_주택유형
train_주택점유형태
train_총생활비
train_총소득
train_가구서비스
train_노인서비스
train_아동서비스
generate_저소득층여부
generate_나이
generate_교육수준
generate_혼인상태
generate_가구형태
generate_주택유형
generate_주택점유형태
generate_총생활비
generate_총소득
generate_가구서비스
generate_노인서비스
generate_아동서비스

In [23]:
synthetic_data_0025.to_csv('synthpop_0025.csv', encoding='UTF-8-sig')
synthetic_data_005.to_csv('synthpop_005.csv', encoding='UTF-8-sig')
synthetic_data_010.to_csv('synthpop_010.csv', encoding='UTF-8-sig')
synthetic_data_020.to_csv('synthpop_020.csv', encoding='UTF-8-sig')
synthetic_data_030.to_csv('synthpop_030.csv', encoding='UTF-8-sig')
synthetic_data_040.to_csv('synthpop_040.csv', encoding='UTF-8-sig')
synthetic_data_050.to_csv('synthpop_050.csv', encoding='UTF-8-sig')
synthetic_data_060.to_csv('synthpop_060.csv', encoding='UTF-8-sig')
synthetic_data_070.to_csv('synthpop_070.csv', encoding='UTF-8-sig')
synthetic_data_080.to_csv('synthpop_080.csv', encoding='UTF-8-sig')
synthetic_data_090.to_csv('synthpop_090.csv', encoding='UTF-8-sig')
synthetic_data_095.to_csv('synthpop_095.csv', encoding='UTF-8-sig')
synthetic_data_0975.to_csv('synthpop_0975.csv', encoding='UTF-8-sig')
synthetic_data_0999.to_csv('synthpop_0999.csv', encoding='UTF-8-sig')